# DFDF (DeepfakeDetectionFramework)
# Author: Jan Bernard (xberna18@stud.fit.vutbr.cz)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfdf-api-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfdf-api
  template:
    metadata:
      labels:
        app: dfdf-api
    spec:
      containers:
        - name: dfdf-api
          image: ghcr.io/playerberny12/vut-dip-code/dfdf-api:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
            limits:
              memory: "1G"
              cpu: "500m"
          volumeMounts:
          - name: processingdata
            mountPath: /mnt/processingdata
      volumes:
      - name: processingdata
        persistentVolumeClaim:
          claimName: processing-data
---
apiVersion: v1
kind: Service
metadata:
  name: dfdf-api-service
spec:
  selector:
    app: dfdf-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
