apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfdf-video-controller-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfdf-video-controller
  template:
    metadata:
      labels:
        app: dfdf-video-controller
    spec:
      containers:
      - name: dfdf-video-controller
        image: ghcr.io/playerberny12/vut-dip-code/dfdf-controller:main
        imagePullPolicy: IfNotPresent
        env:
        - name: RabbitMQ
          value: "rabbitmq-service"
        - name: RabbitMQQueue
          value: "queue_video"
        - name: RabbitMQOutputQueue
          value: "queue_output"
        - name: ProcessingUnitsPorts
          value: "50500:50501"
      - name: dfdf-detection-video-1
        image: ghcr.io/playerberny12/fakevideoforensics/dfdf-detection-video-1:master
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: processingdata
          mountPath: /mnt/processingdata
          readOnly: true
      volumes:
      - name: processingdata
        persistentVolumeClaim:
          claimName: processing-data
          readOnly: true
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dfdf-video-controller-deployment  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dfdf-video-controller-deployment  
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        metric:
          name: rabbitmq_metrics_video_queue_depth
        describedObject:
          kind: Service
          name: rabbitmq-service
          apiVersion: v1
        target:
          type: Value
          averageValue: 2